spring.application.name=festival-scope

naver.client-id=${NAVER_CLIENT_ID}
naver.client-secret=${NAVER_CLIENT_SECRET}
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
tourism.visitor.service-key=${TOURISM_VISITOR_SERVICE_KEY}
tourism.visitor.base-url=https://apis.data.go.kr/B551011/DataLabService
tourism.visitor.endpoint=/locgoRegnVisitrDDList
bus.stop-url=${BUS_STOP_API_URL:https://apis.data.go.kr/1613000/BusStop/getBusStop}
bus.route-url=${BUS_ROUTE_API_URL:https://apis.data.go.kr/1613000/NumberofRoutesServingEachStop/getNumberofRoutesServingEachStop}
bus.route.service-key=${BUS_ROUTE_API_KEY:}
bus.route.operation-date=${BUS_ROUTE_OPERATION_DATE:}
bus.route.ctpv-code=${BUS_ROUTE_CTPV_CODE:}
bus.route.sgg-code=${BUS_ROUTE_SGG_CODE:}
bus.service-key=${BUS_API_KEY}
springdoc.swagger-ui.url=/v3/api-docs
kma.asos.api-key=${KMA_ASOS_API_KEY:}
kma.asos.api-url=${KMA_ASOS_API_URL:https://apis.data.go.kr/1360000/AsosDalyInfoService/getWthrDataList}
kma.asos.analysis-years=${WEATHER_ANALYSIS_YEARS:5}
kma.asos.rain-threshold=${WEATHER_RAIN_THRESHOLD:0}
kma.asos.hot-day-threshold=${HOT_DAY_THRESHOLD:33}
kma.asos.cold-day-threshold=${COLD_DAY_THRESHOLD:-10}
kma.asos.strong-wind-threshold=${STRONG_WIND_THRESHOLD:10}
