package likelion.festivalscope.auth.service;
import likelion.festivalscope.auth.dto.request.*; import likelion.festivalscope.auth.dto.response.*; import likelion.festivalscope.auth.entity.RefreshToken; import likelion.festivalscope.auth.jwt.JwtTokenProvider; import likelion.festivalscope.auth.repository.RefreshTokenRepository; import likelion.festivalscope.global.exception.*; import likelion.festivalscope.user.entity.User; import likelion.festivalscope.user.repository.UserRepository; import lombok.RequiredArgsConstructor; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.LocalDateTime;
@Service @RequiredArgsConstructor
public class AuthService {
 private final UserRepository userRepository; private final RefreshTokenRepository refreshTokenRepository; private final PasswordEncoder passwordEncoder; private final JwtTokenProvider tokenProvider;
 @Transactional public SignupResponse signup(SignupRequest request){if(userRepository.findByEmail(request.email()).isPresent())throw new BusinessException(ErrorCode.AUTH_EMAIL_DUPLICATED); User user=userRepository.save(User.builder().email(request.email()).password(passwordEncoder.encode(request.password())).name(request.name()).build()); return new SignupResponse(user.getUserId(),user.getEmail(),user.getName());}
 @Transactional public LoginResponse login(LoginRequest request){User user=userRepository.findByEmail(request.email()).orElseThrow(()->new BusinessException(ErrorCode.AUTH_INVALID_CREDENTIALS)); if(!passwordEncoder.matches(request.password(),user.getPassword()))throw new BusinessException(ErrorCode.AUTH_INVALID_CREDENTIALS); String access=tokenProvider.createAccessToken(user.getUserId(),user.getEmail()), refresh=tokenProvider.createRefreshToken(user.getUserId()); refreshTokenRepository.findByUser_UserId(user.getUserId()).ifPresentOrElse(r->r.update(refresh,LocalDateTime.now().plusSeconds(tokenProvider.getRefreshExpirationSeconds())),()->refreshTokenRepository.save(RefreshToken.builder().user(user).token(refresh).expiresAt(LocalDateTime.now().plusSeconds(tokenProvider.getRefreshExpirationSeconds())).build())); return new LoginResponse(access,refresh,"Bearer",tokenProvider.getAccessExpirationSeconds(),new MeResponse(user.getUserId(),user.getEmail(),user.getName()));}
 @Transactional public TokenRefreshResponse reissue(TokenRefreshRequest request){RefreshToken saved=refreshTokenRepository.findByToken(request.refreshToken()).orElseThrow(()->new BusinessException(ErrorCode.AUTH_REFRESH_TOKEN_NOT_FOUND)); if(saved.getExpiresAt().isBefore(LocalDateTime.now())||!tokenProvider.isValid(request.refreshToken()))throw new BusinessException(ErrorCode.AUTH_REFRESH_TOKEN_EXPIRED); Long userId=tokenProvider.getUserId(request.refreshToken()); if(!saved.getUser().getUserId().equals(userId))throw new BusinessException(ErrorCode.AUTH_TOKEN_INVALID); User user=userRepository.findById(userId).orElseThrow(()->new BusinessException(ErrorCode.USER_NOT_FOUND)); return new TokenRefreshResponse(tokenProvider.createAccessToken(user.getUserId(),user.getEmail()),"Bearer",tokenProvider.getAccessExpirationSeconds());}
 @Transactional public void logout(TokenRefreshRequest request){refreshTokenRepository.delete(refreshTokenRepository.findByToken(request.refreshToken()).orElseThrow(()->new BusinessException(ErrorCode.AUTH_REFRESH_TOKEN_NOT_FOUND)));}
 @Transactional(readOnly=true) public MeResponse me(Long userId){User user=userRepository.findById(userId).orElseThrow(()->new BusinessException(ErrorCode.USER_NOT_FOUND)); return new MeResponse(user.getUserId(),user.getEmail(),user.getName());}
}
